from django.urls import path, include
from rest_framework.routers import DefaultRouter

from film import views


router = DefaultRouter()
router.register('tags', views.TagViewSet)
router.register('genres', views.GenreViewSet)
router.register('films', views.FilmViewSet)

app_name = 'film'

urlpatterns = [
	# All urls generated by DefaultRouter, will be included in the URL patterns
	path('', include(router.urls))
]