# Generated by Django 4.0.2 on 2022-02-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_film'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('-id',)},
        ),
    ]
